create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  text text not null,
  choices jsonb not null,
  correct integer,
  seconds integer not null default 20 check (seconds between 5 and 120),
  image_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists questions_sort_order_idx on public.questions (sort_order, id);
alter table public.questions enable row level security;
